#! /bin/sh
BRUH
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc config ignore_ewmh_focus true

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

bspc rule -a firefox desktop=^2 focus=on follow=on
bspc rule -a discord desktop='^3' focus=off follow=off
bspc rule -a Spotify desktop='^4' focus=off follow=off # spotify workaround
bspc rule -a spotify-qt desktop='^4' focus=off follow=off
bspc rule -a Steam desktop='^5' focus=off follow=off
bspc rule -a Carla desktop='^10' focus=off follow=off

xrandr --output DP-0 --mode 1920x1080 --rate 144
xrandr --output HDMI-1-1 --mode 1920x1080 --right-of DP-0
xinput --set-prop 'Logitech Gaming Mouse G502' 'libinput Accel Profile Enabled' 0, 1
xsetroot -cursor_name left_ptr &
picom --experimental-backends &
polybar ben-bar &
nitrogen --restore &
/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

discord &
steam &
#cadence &
#$HOME/bin/launch_spotify
spotify-qt &
spotifyd

devilspie &

#bspc config external_rules_command "$HOME/bin/bspwm-external-rules"
